version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./conf/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

  webapp1:
    image: 'wordpress'
    container_name: 'blog1'
    expose:
      - "81"
    environment:
      - "VIRTUAL_HOST=teste.local"
    links:
      - "nginx-proxy"
      
  database-mysql:
    image: 'mysql'
    container_name: 'database-mysql'
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=yyyyy"
      - "MYSQL_ROOT_HOST=0.0.0.0"
      - "MYSQL_USER=xxxxxxx"
      - "MYSQL_PASSWORD=zzzzzzzzzzz"
      - "right=WRITE"
    volumes:
      - /var/www/database/mysql/conf.d:/etc/mysql/conf.d 
      - /var/www/database/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d 
      - /var/www/database/mysql/data:/var/lib/mysql  
      - /var/www/database/mysql/log:/var/log/
